In [1]:
import torch

# 自己给自己赋值

In [2]:
eta1 = torch.nn.Parameter(torch.rand(10), requires_grad=True)
eta1

Parameter containing:
tensor([0.8984, 0.7343, 0.0526, 0.3328, 0.6675, 0.6494, 0.0475, 0.9037, 0.3651,
        0.2628], requires_grad=True)

In [3]:
eta1 = eta1 * 2

In [4]:
eta1

tensor([1.7968, 1.4685, 0.1052, 0.6655, 1.3351, 1.2988, 0.0951, 1.8074, 0.7301,
        0.5257], grad_fn=<MulBackward0>)

In [5]:
eta1.sum().backward()

In [6]:
eta1.grad

/Users/haibinzhao/miniconda3/envs/ML/lib/python3.8/site-packages/torch/_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  /Users/distiller/project/conda/conda-bld/pytorch_1646755922314/work/build/aten/src/ATen/core/TensorBody.h:475.)
  return self._grad


# 赋值给其他变量名

In [7]:
eta2 = torch.nn.Parameter(torch.rand(10), requires_grad=True)
eta2

Parameter containing:
tensor([0.9569, 0.1449, 0.5990, 0.4940, 0.4265, 0.7798, 0.5587, 0.1195, 0.9462,
        0.6785], requires_grad=True)

In [8]:
eta_temp = eta2 * 2

In [9]:
eta_temp

tensor([1.9139, 0.2898, 1.1981, 0.9880, 0.8530, 1.5596, 1.1174, 0.2389, 1.8924,
        1.3569], grad_fn=<MulBackward0>)

In [10]:
eta_temp.sum().backward()

In [11]:
eta2.grad

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

# 直接赋值其他变量

In [12]:
v1 = torch.nn.Parameter(torch.rand(10), requires_grad=True)
v1

Parameter containing:
tensor([0.2398, 0.0752, 0.6915, 0.8748, 0.3743, 0.5317, 0.0245, 0.1415, 0.2035,
        0.3768], requires_grad=True)

In [13]:
a = v1[:4]

In [14]:
a.data.copy_(torch.rand(4))
a

tensor([0.1629, 0.3993, 0.1851, 0.4098], grad_fn=<SliceBackward0>)

In [15]:
v1

Parameter containing:
tensor([0.1629, 0.3993, 0.1851, 0.4098, 0.3743, 0.5317, 0.0245, 0.1415, 0.2035,
        0.3768], requires_grad=True)

# 克隆给其他

In [16]:
v2 = torch.nn.Parameter(torch.rand(10), requires_grad=True)
v2

Parameter containing:
tensor([0.7166, 0.6798, 0.3551, 0.9799, 0.2783, 0.6407, 0.0289, 0.5479, 0.6294,
        0.4445], requires_grad=True)

In [17]:
b = v2[:4].clone()

In [18]:
b.data.copy_(torch.rand(4))
b

tensor([0.4646, 0.6014, 0.3515, 0.4656], grad_fn=<CloneBackward0>)

In [19]:
v2

Parameter containing:
tensor([0.7166, 0.6798, 0.3551, 0.9799, 0.2783, 0.6407, 0.0289, 0.5479, 0.6294,
        0.4445], requires_grad=True)

# 先生成变量，再用torch.no_grad()

In [20]:
t = torch.nn.Parameter(torch.randn(12,1), requires_grad=True)
t

Parameter containing:
tensor([[-0.4392],
        [ 0.9208],
        [-2.1834],
        [ 0.7074],
        [ 0.4114],
        [ 0.6539],
        [ 1.3077],
        [-1.2103],
        [-0.6207],
        [-0.6490],
        [ 0.7914],
        [ 0.2057]], requires_grad=True)

In [21]:
with torch.no_grad():
    t = t.view(3,4)
t

tensor([[-0.4392,  0.9208, -2.1834,  0.7074],
        [ 0.4114,  0.6539,  1.3077, -1.2103],
        [-0.6207, -0.6490,  0.7914,  0.2057]], requires_grad=True)

In [22]:
t.sum().backward()

In [23]:
t.grad

# 先初始化，再生成变量

In [24]:
k = torch.randn(12,1)
k

tensor([[ 0.5310],
        [ 0.4474],
        [-0.1015],
        [-1.0698],
        [-0.4346],
        [ 0.1871],
        [-0.5165],
        [ 0.2802],
        [ 0.2573],
        [-0.3759],
        [ 0.2647],
        [-0.3205]])

In [25]:
k = k.view(3,4)

In [26]:
kp = torch.nn.Parameter(k, requires_grad=True)

In [27]:
kp.sum().backward()

In [28]:
kp.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])